// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kattsnupukjwyasjhxyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthdHRzbnVwdWtqd3lhc2poeHl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNzc5NTAsImV4cCI6MjA2Nzg1Mzk1MH0.pCRQ7OvQAC046J5E9XB4QRBmqLwQA7-N6JgHA1_Z_nE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});